# Generated by Django 4.0.4 on 2022-05-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_room_thumb_room_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='namee',
        ),
    ]
