# Generated by Django 4.0.4 on 2022-05-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_name_topic_namee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='namee',
            new_name='name',
        ),
    ]
